### ISSUE TITLE
ActiveRecordFindReturnTypeExtension fails if class provided through variable

### ISSUE THREAD

**Issue by dotterian** [erickskrauch/phpstan-yii2#1]
This little part of code breaks the rule:
```php
$class = Article::class;
if ($type === 'news') {
    $class = News::class;
}
$items = $class::find();
```

Rule is expecting class name to be `PhpParser\Node\Name` but instead `PhpParser\Node\Expr\Variable` is provided.

I think it could be fixed by adding check and changing return type of function to `?Type`, like this:
```php
public function getTypeFromStaticMethodCall(MethodReflection $methodReflection, StaticCall $methodCall, Scope $scope): ?Type {
    $className = $methodCall->class;
    if (!($className instanceof Name)) {
        return null;
    }
    $name = $scope->resolveName($className);
    /** @var \PHPStan\Type\ObjectType $returnType */
    $returnType = ParametersAcceptorSelector::selectSingle($methodReflection->getVariants())->getReturnType();

    return new ActiveQueryObjectType($name, $returnType->getClassName());
}
```

Alternative would be to get all possible variable values, treat them like class-string and provide them as return value through union type. But I'm not familiar with PHPStan enough to write this, and, honestly, think that this may be impossible or at least too difficult in some cases.

**Comment by erickskrauch** [comment]
First of all, thank you for the issue. I'm glad that this extension is already useful for someone except myself even the fact that I didn't published it on the packagist yet 😅

I'm also not very deeply familiar with PHPStan's internal types structure so I really expect some of such errors since I can't imagine every possible use-case. I'll fix this issue with the help of your suggested code.

Feel free to report more errors from your projects.

**Comment by erickskrauch** [comment]
I was able to fix it just so it wouldn't cause an error. I also found a way to derive the type from constant strings, so I think I can still make the typing work in the above code example. It just takes time.
